### ISSUE TITLE
Direct function call inside Composable 

### ISSUE THREAD

**Issue by LavishSwarnkar** [Code3six/FaangX#2]
getLogin() - Direct function call inside Composable
https://github.com/Code3six/FaangX/blob/49bb53c512b23791f3f3a751eabe130f62362e73/app/src/main/java/com/example/faangx/presentation/ui/screens/splash/SplashScreen.kt#L38
- Please use LaunchedEffect for calling such functions otherwise they will be unnecessarily called multiple times on each recomposition.

**Comment by Code3six** [comment]
Done
