### ISSUE TITLE
User fields saved separately in datastore

### ISSUE THREAD

**Issue by LavishSwarnkar** [Code3six/FaangX#3]
- You have created so many set*() funtions in ViewModel to read user data from Datastore. Use serialization & deserialization (gson) to read/write user object.
- Also, no need of log boolean (isLoggedIn). We can use user object to determine that. If (user != null) i.e. user is available, then loggedIn else not.

https://github.com/Code3six/FaangX/blob/49bb53c512b23791f3f3a751eabe130f62362e73/app/src/main/java/com/example/faangx/presentation/viewmodel/SharedViewModel.kt#L90-L99
https://github.com/Code3six/FaangX/blob/49bb53c512b23791f3f3a751eabe130f62362e73/app/src/main/java/com/example/faangx/presentation/viewmodel/SharedViewModel.kt#L144-L158

**Comment by Code3six** [comment]
changed setName, setPhone, etc.. to setAll

**Comment by LavishSwarnkar** [comment]
You are still saving and reading each field separately in datastore : 
https://github.com/Code3six/FaangX/blob/d1664261ebe08d1a845db72f62956488509235f1/app/src/main/java/com/example/faangx/presentation/viewmodel/SharedViewModel.kt#L142-L157

Please read the issue described earlier carefully : **"Use serialization & deserialization (gson) to read/write user object"** .
You must be saving only one string in the datastore i.e. user. It will contain the entire user object. No need to write & read separately.
