### ISSUE TITLE
Not saving profile on Firestore

### ISSUE THREAD

**Issue by LavishSwarnkar** [Code3six/FaangX#4]
- You are not saving user profile on Firestore. Read the [app doc](https://www.notion.so/Phase-1-Profile-5d2d16442e414d79b358bcec08fa07c0#4cff03646dcc43bd99160195fe7a8fec) for specification. 
- Also, after login app always navigates to editProfile. It should go to editProfile only if profile is yet to be created & saved on Firestore. If already done, it should navigate to home.

**Comment by Code3six** [comment]
ok
