### ISSUE TITLE
Duplicate states in Composable

### ISSUE THREAD

**Issue by LavishSwarnkar** [Code3six/FaangX#6]
https://github.com/Code3six/FaangX/blob/49bb53c512b23791f3f3a751eabe130f62362e73/app/src/main/java/com/example/faangx/presentation/ui/screens/editprofile/EditProfileContent.kt#L48-L58
- Why have you recreated same states in Composable - EditProfileContent, when they already exist in SharedViewModel? You can directly use the states from ViewModel.

**Comment by Code3six** [comment]
So they can be rewritten on onTextChange().
